import type { Metadata } from "next";
import Header from "@/componens/header";
import Link from 'next/link'
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
      </head>
      <body>
        <header>
          <Header/>
        </header>
        {modal}     
        {children}
      </body>
    </html>
  );
}
